.POSIX:

# This Makefile was generated by maje
# See https://gitlab.com/jkaivo/maje/ for more information
# Do not edit this Makefile by hand

CC=c99
LD=$(CC)
CFLAGS=-Wall -Wextra -Wpedantic -Werror -g
LDFLAGS=
LDLIBS=
SRCDIR=.
OBJDIR=.
BINDIR=$(OBJDIR)

all: $(BINDIR)/more

clean:
	rm -f $(BINDIR)/more $(OBJDIR)/*.o

$(BINDIR)/more: $(OBJDIR)/io.o
$(OBJDIR)/io.o: $(SRCDIR)/more.h
$(OBJDIR)/io.o: $(SRCDIR)/io.c
	$(CC) $(CFLAGS) -o $@ -c $(SRCDIR)/io.c

$(BINDIR)/more: $(OBJDIR)/more.o
$(OBJDIR)/more.o: $(SRCDIR)/more.h
$(OBJDIR)/more.o: $(SRCDIR)/more.c
	$(CC) $(CFLAGS) -o $@ -c $(SRCDIR)/more.c

$(BINDIR)/more: $(OBJDIR)/tty.o
$(OBJDIR)/tty.o: $(SRCDIR)/more.h
$(OBJDIR)/tty.o: $(SRCDIR)/tty.c
	$(CC) $(CFLAGS) -o $@ -c $(SRCDIR)/tty.c

$(BINDIR)/more:
	$(LD) $(LDFLAGS) -o $@ $(OBJDIR)/*.o $(LDLIBS)
